name: Manual review test

permissions:
  contents: read

on : workflow_dispatch

jobs:
  deploy :
    runs-on: ubuntu-latest
    environment: Prod
    steps:
     - name: 📥 Checkout Repository
       uses: actions/checkout@v3
    
    
